"""Export generation service — Markdown, HTML, and JSON formats."""

from __future__ import annotations

import html
import json
import logging
from datetime import datetime, timezone, timedelta
from typing import Any, Optional

logger = logging.getLogger(__name__)


def generate_markdown_export(analysis: dict[str, Any]) -> tuple[str, str]:
    """Generate a Markdown-formatted PRD export.

    Returns ``(content, filename)``.
    """
    prd = analysis.get("prd", {})
    overview = prd.get("overview", {})
    scope = prd.get("scope", {})
    constraints = prd.get("technical_constraints", {})

    lines = [
        f"# {prd.get('title', 'Project Specification Document')}",
        "",
        f"**Version:** {prd.get('version', '1.0')}",
        f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        f"**Domain:** {overview.get('project_type', 'Unknown')}",
        f"**RMS Score:** {analysis.get('rms', 'N/A')}/100",
        "",
        "## Overview",
        "",
        overview.get("summary", "No summary available."),
        "",
        "## Target Users",
        "",
    ]

    for user in analysis.get("implied_users", []):
        lines.append(f"- {user}")
    lines.append("")

    lines.extend([
        "## Scope",
        "",
        "### In Scope",
        "",
    ])
    for item in scope.get("in_scope", []):
        lines.append(f"- {item}")
    lines.append("")

    lines.extend(["### Out of Scope", ""])
    for item in scope.get("out_of_scope", []):
        lines.append(f"- {item}")
    lines.append("")

    lines.extend(["## Functional Requirements", ""])
    for i, req in enumerate(prd.get("functional_requirements", []), 1):
        lines.append(f"{i}. {req}")
    lines.append("")

    lines.extend(["## Non-Functional Requirements", ""])
    for key, value in prd.get("non_functional", {}).items():
        lines.append(f"- **{key.title()}:** {value}")
    lines.append("")

    if constraints.get("tech_stack"):
        lines.extend(["## Technology Stack", "", constraints["tech_stack"], ""])

    if constraints.get("timeline"):
        lines.extend(["## Estimated Timeline", "", constraints["timeline"], ""])

    lines.extend(["## Risks", ""])
    for risk in prd.get("risks", []):
        lines.append(f"- {risk}")
    lines.append("")

    lines.extend(["## Clarification Questions", ""])
    for i, q in enumerate(analysis.get("clarification_questions", []), 1):
        lines.append(f"{i}. {q}")
    lines.append("")

    lines.extend(["## Missing Features", ""])
    for feature in analysis.get("missing_features", []):
        lines.append(f"- [ ] {feature}")
    lines.append("")

    if analysis.get("conflicts"):
        lines.extend(["## Conflicts & Tensions", ""])
        for conflict in analysis["conflicts"]:
            lines.append(f"> ⚠️ {conflict}")
        lines.append("")

    lines.extend(["---", "", f"*Generated by SpecForge*", ""])

    content = "\n".join(lines)
    filename = f"prd-{analysis.get('domain', 'project')}-{datetime.now(timezone.utc).strftime('%Y%m%d')}.md"
    return content, filename


def generate_html_export(analysis: dict[str, Any]) -> tuple[str, str]:
    """Generate an HTML-formatted PRD export suitable for printing or PDF conversion.

    Returns ``(content, filename)``.
    """
    prd = analysis.get("prd", {})
    overview = prd.get("overview", {})
    scope = prd.get("scope", {})
    constraints = prd.get("technical_constraints", {})

    # Escape helper — use html.escape for XSS prevention
    _esc = html.escape

    def _list_items(items):
        return "".join(f"<li>{_esc(str(item))}</li>" for item in items)

    title = _esc(prd.get("title", "Project Specification Document"))
    version = _esc(prd.get("version", "1.0"))
    domain = _esc(overview.get("project_type", "Unknown"))
    rms = _esc(str(analysis.get("rms", "N/A")))
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    summary = _esc(overview.get("summary", "No summary available."))

    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; line-height: 1.6; color: #1a1a1a; }}
h1 {{ border-bottom: 2px solid #2563eb; padding-bottom: 0.5rem; color: #1e3a5f; }}
h2 {{ color: #2563eb; margin-top: 2rem; }}
h3 {{ color: #4b5563; }}
.meta {{ color: #6b7280; font-size: 0.9rem; margin-bottom: 2rem; }}
.rms {{ display: inline-block; background: #2563eb; color: white; padding: 0.25rem 0.75rem; border-radius: 9999px; font-weight: bold; }}
.in-scope li {{ color: #065f46; }}
.out-scope li {{ color: #991b1b; text-decoration: line-through; }}
.question {{ background: #f3f4f6; padding: 0.75rem 1rem; border-radius: 0.5rem; margin: 0.5rem 0; }}
.conflict {{ background: #fef3c7; border-left: 4px solid #f59e0b; padding: 0.75rem 1rem; margin: 0.5rem 0; }}
footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 0.85rem; text-align: center; }}
@media print {{ body {{ padding: 0; max-width: none; }} }}
</style>
</head>
<body>
<h1>{title}</h1>
<div class="meta">
<strong>Version:</strong> {version} &middot;
<strong>Domain:</strong> {domain} &middot;
<strong>RMS:</strong> <span class="rms">{rms}/100</span> &middot;
<strong>Generated:</strong> {generated}
</div>

<h2>Overview</h2>
<p>{summary}</p>

<h2>Target Users</h2>
<ul>{_list_items(analysis.get("implied_users", []))}</ul>

<h2>Scope</h2>
<h3>In Scope</h3>
<ul class="in-scope">{_list_items(scope.get("in_scope", []))}</ul>
<h3>Out of Scope</h3>
<ul class="out-scope">{_list_items(scope.get("out_of_scope", []))}</ul>

<h2>Functional Requirements</h2>
<ol>{_list_items(prd.get("functional_requirements", []))}</ol>

<h2>Non-Functional Requirements</h2>
<ul>
"""
    for key, value in prd.get("non_functional", {}).items():
        html_content += f"<li><strong>{_esc(key.title())}:</strong> {_esc(str(value))}</li>\n"

    html_content += "</ul>\n"

    if constraints.get("tech_stack"):
        html_content += f"<h2>Technology Stack</h2>\n<p>{_esc(str(constraints['tech_stack']))}</p>\n"
    if constraints.get("timeline"):
        html_content += f"<h2>Estimated Timeline</h2>\n<p>{_esc(str(constraints['timeline']))}</p>\n"

    html_content += "<h2>Risks</h2>\n<ul>\n"
    for risk in prd.get("risks", []):
        html_content += f"<li>{_esc(str(risk))}</li>\n"
    html_content += "</ul>\n"

    html_content += "<h2>Clarification Questions</h2>\n"
    for q in analysis.get("clarification_questions", []):
        html_content += f'<div class="question">{_esc(str(q))}</div>\n'

    if analysis.get("missing_features"):
        html_content += "<h2>Missing Features</h2>\n<ul>\n"
        for f in analysis["missing_features"]:
            html_content += f"<li>☐ {_esc(str(f))}</li>\n"
        html_content += "</ul>\n"

    if analysis.get("conflicts"):
        html_content += "<h2>Conflicts &amp; Tensions</h2>\n"
        for c in analysis["conflicts"]:
            html_content += f'<div class="conflict">⚠️ {_esc(str(c))}</div>\n'

    html_content += """
<footer>Generated by SpecForge &middot; specforge.dev</footer>
</body>
</html>"""

    filename = f"prd-{analysis.get('domain', 'project')}-{datetime.now(timezone.utc).strftime('%Y%m%d')}.html"
    return html_content, filename


def generate_json_export(analysis: dict[str, Any]) -> tuple[str, str]:
    """Generate a structured JSON export.

    Returns ``(content, filename)``.
    """
    export_data = {
        "metadata": {
            "title": "Project Specification Document",
            "version": "1.0",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "generator": "SpecForge",
        },
        "analysis": {
            "domain": analysis.get("domain"),
            "rms": analysis.get("rms"),
            "implied_users": analysis.get("implied_users", []),
            "missing_features": analysis.get("missing_features", []),
            "clarification_questions": analysis.get("clarification_questions", []),
            "conflicts": analysis.get("conflicts", []),
        },
        "prd": analysis.get("prd", {}),
    }

    content = json.dumps(export_data, indent=2, ensure_ascii=False)
    filename = f"prd-{analysis.get('domain', 'project')}-{datetime.now(timezone.utc).strftime('%Y%m%d')}.json"
    return content, filename


# Format registry
EXPORT_FORMATS = {
    "markdown": generate_markdown_export,
    "html": generate_html_export,
    "json": generate_json_export,
}

SUPPORTED_FORMATS = list(EXPORT_FORMATS.keys())


def generate_export(analysis: dict[str, Any], fmt: str = "markdown") -> tuple[str, str]:
    """Generate an export in the specified format.

    Returns ``(content, filename)``.
    Raises ValueError for unsupported formats.
    """
    fmt = fmt.lower()
    if fmt not in EXPORT_FORMATS:
        raise ValueError(f"Unsupported format '{fmt}'. Supported: {SUPPORTED_FORMATS}")

    return EXPORT_FORMATS[fmt](analysis)
